server:
  servlet:
    context-path: /UniversityPortal
spring:
  jackson:
    default-property-inclusion: non_empty
    serialization.FAIL_ON_EMPTY_BEANS: false
  application:
    name: UniversityPortal
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/university_portal
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redission/redission-postgresdev.yml
jwt:
  expiresInMinute: 10
  secretKey: mbA7W_&3Gg'a'{.Z!@4724:%=rF.YjuA