server:
  servlet:
    context-path: /UniversityPortal
spring:
  jackson:
    default-property-inclusion: non_empty
    serialization.FAIL_ON_EMPTY_BEANS: false
  application:
    name: UniversityPortal
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: manjitshakya
    password: 1218
    url: jdbc:postgresql://localhost:5432/university_portal
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  expiresInMinute: 30
  secretKey: mbA7W_&3Gg'a'{.Z!@4724:%=rF.YjuA