server:
  servlet:
    context-path: /UniversityPortal
spring:
  jackson:
    default-property-inclusion: non_empty
    serialization.FAIL_ON_EMPTY_BEANS: false
  application:
    name: UniversityPortal
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
    url: jdbc:mysql://localhost:3306/UNIVERSITY_PORTAL?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  expiresInMinute: 10
  secretKey: mbA7W_&3Gg'a'{.Z!@4724:%=rF.YjuA

