spring:
  application:
    name: sms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
    url: jdbc:mysql://localhost:3306/UP?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create