server:
  servlet:
    context-path: /UniversityPortal

spring:
  application:
    name: UniversityPortal
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sapana
    password: sapana
    url: jdbc:mysql://localhost:3306/UNIVERSITY_PORTAL?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

